<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>sanber bacth 53</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3f248379-8c79-4938-aa9a-3bdcfd8c4a44</testSuiteGuid>
   <testCaseLink>
      <guid>37701a2d-9f24-4934-8a54-02025bed8b5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/1. Login username-password is true</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca466aa0-fc3b-42c4-898e-b7dc58ced5ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ddb6f78-843a-4c99-b840-17aeed54810e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18039a11-33be-4f98-949c-164de0f88a2a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/2. Login username-password is wrong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acee5d28-b217-4c16-aa5b-9563ecee1d6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35c34617-e021-41d1-b4e2-9bf490ad38b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>86c46c67-0b16-4b80-9d61-1c716d7b0215</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/3. Login username-password no fill placeholder</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f37d5332-08a8-45ab-9f48-6a7a08f9dfe5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d2a8f1a-2631-45e5-a51f-c211769d6f3c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>655826e9-9802-47a3-8a30-2707ee254399</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/4. Login user input username is true and input password is wrong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d25b49fa-e5a8-478c-bd38-ea57b030474e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7722b38a-0ea3-4528-a59e-63798560a0f4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
